[package]
edition = "2021"
name = "checkers-app"
version = "0.4.1"

[dependencies]
bevy = { version = "0.9.0" }
bevy_tasks = "0.9.0"
bevy_mod_picking = { version = "0.11.0" }
bevy_tweening = { version = "0.6.0" }
futures = "0.3"
checkers-ai = { path = "../checkers-ai" }
checkers-core = { path = "../checkers-core" }
