[package]
edition = "2021"
name = "checkers-app"
version = "0.2.0"

[dependencies]
bevy = { version = "0.8.1" }
bevy_tasks = "0.8.1"
bevy-inspector-egui = { version = "0.13.0" }
bevy_mod_picking = { version = "0.9.0" }
bevy_tweening = { version = "0.5.0" }
futures = "0.3"
checkers-ai = { path = "../checkers-ai", version = "^0.2.0" }
checkers-core = { path = "../checkers-core", version = "^0.2.0" }
