[package]
edition = "2021"
name = "checkers-app"
version = "0.5.0"

[dependencies]
bevy = { version = "0.11" }
bevy_tasks = "0.11"
bevy_mod_picking = { version = "0.15", features = ["default"] }
bevy_tweening = { version ="0.8" }
futures = "0.3"
checkers-ai = { path = "../checkers-ai" }
checkers-core = { path = "../checkers-core" }
