[package]
edition = "2021"
name = "checkers-core"
version = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = "1.0"
bevy = {version = "0.6.0"}
serde = "1.0.136"
serde_json = "1.0"
