[package]
edition = "2021"
name = "checkers-p2p"
version = "0.6.0"

[dependencies]
bevy = { version = "0.12" }
checkers-core = { path = "../checkers-core" }
checkers-app = { path = "../checkers-app" }
