[package]
edition = "2021"
name = "checkers-p2p"
version = "0.6.0"

[dependencies]
bevy = { version = "0.11" }
futures = "0.3"
checkers-ai = { path = "../checkers-ai" }
checkers-core = { path = "../checkers-core" }
checkers-app = { path = "../checkers-app" }
